### ISSUE TITLE
Would you please add support for the steam version?

### ISSUE THREAD

**Issue by funduke** [kevansevans/Unity-Doom-Ripper#3]
Would you please add support for the steam version?

Greetings
Funduke

**Comment by kevansevans** [comment]
The wads are exposed in the steam version under the folder "SteamLibrary\steamapps\common\[Doom or Doom 2]\rerelease\Doom or Doom 2]\StreamingAssets"

There's no longer a need to maintain this program for future purposes.

**Comment by funduke** [comment]
Only the IWADs of Ultimate DooM and DooM II are in the StreamingAssets -directories, but not those of the downloadable content WADs.
Is there a solution for this?

Greetings
Funduke

**Comment by kevansevans** [comment]
The downloadable wads are located within a windows save directory and not something stored within the games assets folder, which is in the same location for both the Bethesda launcher and Steam versions. The program is still capable of grabbing those wads. You can manually copy these files from ``C:\Users\[Username]\Saved Games\id Software\[Doom or Doom 2] Classic\WADs``
